id: PD7E76D8C
initial_creation_type: input
source_metadata:
  title: Gaṅgottaraparipṛcchā
  language: en
  volumes:
    7c608039f96c4a91b38867c1f5ba8353:
      title: Colophon
      base_file: Colophon.txt
      work_id: WAA621C40
    892c4a46a2d149069093ee29cd38113d:
      title: Preface
      base_file: Preface.txt
      work_id: W02534384
    fdce4292dc2648d6bb4c856bb0339a45:
      title: Title
      base_file: Title.txt
      work_id: WAD0192E8
  chapter_to_tile: {}
created_at: '2022-03-01T21:28:48.444389'
last_modified_at: '2022-03-01T21:28:48.444396'
